apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_AUTH_URL
              value: http://pomodoro.local/auth/api/auth
            - name: REACT_APP_TIMER_URL
              value: http://pomodoro.local/timer/api
            - name: REACT_APP_TASK_URL
              value: http://pomodoro.local/task/api